/**
 * Insurance Agency Italy — Document Type Definitions
 *
 * Covers documents for a general insurance agency:
 * policies, claims, expert assessments, medical certificates,
 * repair invoices, authority reports, and more.
 *
 * 15 document types for multi-branch insurance management.
 */
import type { DocumentTypeDef } from '../../../types';
import {
    text, num, date, enumField, objectSchema, arrayOfObjects,
    nome, cognome, codiceFiscale, targa, telaio,
} from '../../../helpers/it';

// ─── Document IDs ───────────────────────────────────────────────────────────

export const DOC_IDS = {
    IDENTITA: 'doc-identita',
    TESSERA_SANITARIA: 'doc-tessera-sanitaria',
    POLIZZA: 'doc-polizza',
    ATTESTATO_RISCHIO: 'doc-attestato-rischio',
    LIBRETTO: 'doc-libretto',
    DENUNCIA_SINISTRO: 'doc-denuncia-sinistro',
    PERIZIA_DANNI: 'doc-perizia-danni',
    CERTIFICATO_MEDICO: 'doc-certificato-medico',
    FATTURA_RIPARAZIONE: 'doc-fattura-riparazione',
    VERBALE_AUTORITA: 'doc-verbale-autorita',
    QUIETANZA: 'doc-quietanza',
    DISDETTA: 'doc-disdetta',
    STATO_FAMIGLIA: 'doc-stato-famiglia',
    CERTIFICATO_MORTE: 'doc-certificato-morte',
    SCHEDA_FABBRICATO: 'doc-scheda-fabbricato',
} as const;

// ─── Document Types ─────────────────────────────────────────────────────────

export const documentTypes: DocumentTypeDef[] = [
    {
        id: DOC_IDS.IDENTITA,
        name: "Documento d'Identità",
        description: "Documento di riconoscimento dell'assicurato (CI, Passaporto, Patente)",
        isArrayExtraction: true,
        jsonSchema: objectSchema({
            nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            tipoDocumento: text("Tipo documento: Carta D'Identità, Passaporto, Patente"),
            numeroDocumento: text(''),
            dataEmissione: date('Data di emissione in formato DD.MM.YYYY'),
            dataScadenza: date('Data di scadenza in formato DD.MM.YYYY'),
            rilasciatoDa: text('Autorità che ha rilasciato il documento'),
            luogoNascita: text("Città seguita dalla sigla della provincia tra parentesi tonde — formato: 'NomeCittà (XX)'"),
            dataNascita: date('Data di nascita in formato DD.MM.YYYY'),
            indirizzoDiResidenza: text('Indirizzo completo di residenza'),
        }, ['nome', 'cognome', 'codiceFiscale', 'tipoDocumento', 'numeroDocumento', 'dataEmissione', 'dataScadenza', 'luogoNascita', 'dataNascita']),
    },
    {
        id: DOC_IDS.TESSERA_SANITARIA,
        name: 'Tessera Sanitaria',
        description: 'Tessera sanitaria / Codice Fiscale — conferma CF e dati anagrafici',
        isArrayExtraction: true,
        jsonSchema: objectSchema({
            nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            sesso: enumField('Sesso', ['M', 'F']),
            dataNascita: date('Data di nascita'),
            luogoNascita: text('Comune di nascita'),
            dataScadenza: date('Data di scadenza'),
        }, ['nome', 'cognome', 'codiceFiscale', 'sesso', 'dataNascita']),
    },
    {
        id: DOC_IDS.POLIZZA,
        name: 'Polizza Assicurativa',
        description: 'Contratto di assicurazione — tutti i rami (RCA, vita, casa, infortuni, RC professionale)',
        jsonSchema: objectSchema({
            compagnia: text('Compagnia assicurativa'),
            numeroPolizza: text('Numero polizza'),
            ramo: enumField('Ramo assicurativo', ['RCA', 'vita', 'casa', 'infortuni', 'RC professionale', 'salute', 'furto/incendio', 'kasko', 'trasporti', 'altro']),
            contraente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                indirizzo: text('Indirizzo del contraente'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            assicurato: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            targa: targa(),
            premioAnnuo: num('Premio annuo totale in Euro'),
            premioSemestrale: num('Premio semestrale in Euro (se frazionato)'),
            decorrenza: date('Data decorrenza copertura'),
            scadenza: date('Data scadenza copertura'),
            massimale: text('Massimale di copertura (es. Euro 6.450.000)'),
            franchigia: text('Eventuale franchigia o scoperto'),
            garanzie: text('Elenco garanzie incluse (separare con virgola)'),
            beneficiario: text('Beneficiario designato (per polizze vita)'),
        }, ['compagnia', 'numeroPolizza', 'ramo', 'contraente', 'premioAnnuo', 'decorrenza', 'scadenza']),
    },
    {
        id: DOC_IDS.ATTESTATO_RISCHIO,
        name: 'Attestato di Rischio',
        description: 'Attestato di rischio RCA — classe di merito, sinistri pregressi',
        jsonSchema: objectSchema({
            compagnia: text('Compagnia assicurativa emittente'),
            contraente: text('Nome e cognome del contraente'),
            codiceFiscaleContraente: codiceFiscale(),
            targa: targa(),
            classeMeritoProvenienza: text('Classe di merito CU provenienza'),
            classeMeritoAssegnazione: text('Classe di merito CU assegnazione'),
            sinistri: arrayOfObjects({
                anno: num('Anno del sinistro'),
                responsabilita: enumField('Tipo responsabilità', ['principale', 'paritaria', 'nessuna']),
                tipo: text('Tipo sinistro (cose, persone)'),
                importo: num('Importo liquidato in Euro'),
            }, ['anno', 'responsabilita'], 'Tabella sinistri ultimi 5 anni'),
            anniAssicurazione: num('Anni di osservazione assicurativa'),
            dataEmissione: date('Data emissione attestato'),
        }, ['compagnia', 'contraente', 'targa', 'classeMeritoProvenienza', 'classeMeritoAssegnazione']),
    },
    {
        id: DOC_IDS.LIBRETTO,
        name: 'Libretto di Circolazione',
        description: 'Carta di circolazione del veicolo assicurato',
        jsonSchema: objectSchema({
            targa: targa(), telaio: telaio(),
            marca: text('Marca del veicolo'), modello: text('Modello del veicolo'),
            cilindrata: num('Cilindrata in cc'),
            potenzaKw: num('Potenza in kW'),
            alimentazione: enumField('Tipo alimentazione', ['benzina', 'diesel', 'GPL', 'metano', 'ibrido', 'elettrico']),
            dataImmatricolazione: date('Data di prima immatricolazione'),
            intestatario: text('Nome e cognome/ragione sociale intestatario'),
            codiceFiscaleIntestatario: codiceFiscale(),
        }, ['targa', 'telaio', 'marca', 'modello', 'dataImmatricolazione', 'intestatario']),
    },
    {
        id: DOC_IDS.DENUNCIA_SINISTRO,
        name: 'Denuncia Sinistro / CID',
        description: 'Constatazione amichevole (CAI/CID) o denuncia sinistro — dinamica, danni, veicoli',
        jsonSchema: objectSchema({
            numeroSinistro: text('Numero sinistro assegnato dalla compagnia (se già presente)'),
            dataSinistro: date('Data del sinistro'),
            oraSinistro: text('Ora del sinistro (es. 14:30)'),
            luogoSinistro: text('Luogo del sinistro (indirizzo, comune, provincia)'),
            dinamica: text("Descrizione della dinamica dell'incidente — copia VERBATIM dal modulo"),
            veicoloA: objectSchema({
                targa: targa(), marca: text('Marca'), modello: text('Modello'),
                contraente: text('Nome cognome contraente'),
                codiceFiscale: codiceFiscale(),
                compagnia: text('Compagnia assicurativa'),
                numeroPolizza: text('Numero polizza'),
                danni: text('Danni visibili al veicolo A'),
            }, ['targa', 'contraente']),
            veicoloB: objectSchema({
                targa: targa(), marca: text('Marca'), modello: text('Modello'),
                contraente: text('Nome cognome contraente'),
                codiceFiscale: text('Codice fiscale del contraente B'),
                compagnia: text('Compagnia assicurativa'),
                numeroPolizza: text('Numero polizza'),
                danni: text('Danni visibili al veicolo B'),
            }, ['targa']),
            feriti: enumField('Presenza di feriti', ['sì', 'no']),
            testimoni: text('Eventuali testimoni (nome e cognome)'),
            autoritaIntervenuta: enumField('Autorità intervenuta', ['Polizia Stradale', 'Carabinieri', 'Polizia Municipale', 'nessuna']),
        }, ['dataSinistro', 'luogoSinistro', 'dinamica', 'veicoloA']),
    },
    {
        id: DOC_IDS.PERIZIA_DANNI,
        name: 'Perizia Danni',
        description: 'Perizia tecnica dei danni — importo, descrizione danni, perito',
        jsonSchema: objectSchema({
            numeroSinistro: text('Numero sinistro di riferimento'),
            perito: text('Nome e cognome del perito'),
            studioPeritale: text('Studio peritale incaricato'),
            targa: targa(),
            dataPerizia: date('Data della perizia'),
            danni: text('Descrizione dettagliata dei danni riscontrati'),
            importoRiparazione: num('Importo stimato per la riparazione in Euro'),
            importoLiquidazione: num('Importo proposto per la liquidazione in Euro'),
            demolizione: enumField('Veicolo da demolire', ['sì', 'no']),
            valoreAntesinistro: num('Valore del veicolo ante-sinistro in Euro'),
            fotografieAllegate: enumField('Fotografie allegate', ['sì', 'no']),
        }, ['numeroSinistro', 'perito', 'targa', 'danni', 'importoRiparazione']),
    },
    {
        id: DOC_IDS.CERTIFICATO_MEDICO,
        name: 'Certificato Medico',
        description: 'Certificato medico per lesioni da sinistro o infortunio coperto da polizza',
        jsonSchema: objectSchema({
            paziente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                dataNascita: date('Data di nascita'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            medico: text('Nome e cognome del medico'),
            struttura: text('Struttura sanitaria / ospedale'),
            dataVisita: date('Data della visita/referto'),
            diagnosi: text('Diagnosi — copia VERBATIM dal certificato'),
            prognosi: text('Prognosi — giorni di guarigione o invalidità'),
            giorniPrognosi: num('Numero giorni di prognosi'),
            invaliditaPermanente: num('Percentuale di invalidità permanente (se indicata)'),
            terapiaPrescritta: text('Terapia prescritta'),
        }, ['paziente', 'medico', 'dataVisita', 'diagnosi']),
    },
    {
        id: DOC_IDS.FATTURA_RIPARAZIONE,
        name: 'Fattura di Riparazione',
        description: "Fattura dell'officina/carrozzeria per riparazione danni",
        jsonSchema: objectSchema({
            officina: text('Denominazione officina/carrozzeria'),
            partitaIva: text('Partita IVA officina'),
            numero: text('Numero fattura'),
            data: date('Data fattura'),
            targa: targa(),
            lavorazioni: text('Descrizione lavorazioni eseguite'),
            ricambi: text('Elenco ricambi utilizzati'),
            manodopera: num('Costo manodopera in Euro'),
            costoRicambi: num('Costo ricambi in Euro'),
            imponibile: num('Totale imponibile in Euro'),
            iva: num('IVA in Euro'),
            totale: num('Totale fattura in Euro'),
        }, ['officina', 'numero', 'data', 'targa', 'totale']),
    },
    {
        id: DOC_IDS.VERBALE_AUTORITA,
        name: 'Verbale Autorità',
        description: 'Verbale di Polizia Stradale, Carabinieri o Polizia Municipale',
        jsonSchema: objectSchema({
            autorita: text('Autorità che ha redatto il verbale'),
            dataVerbale: date('Data del verbale'),
            luogo: text("Luogo dell'intervento"),
            numeroVerbale: text('Numero protocollo verbale'),
            veicoliCoinvolti: arrayOfObjects({
                targa: targa(), conducente: text('Nome e cognome del conducente'),
            }, ['targa'], 'Veicoli coinvolti'),
            contravvenzioni: text('Eventuali contravvenzioni contestate'),
            rilievi: text("Rilievi e osservazioni dell'autorità — copia VERBATIM"),
            feriti: enumField('Feriti segnalati', ['sì', 'no']),
        }, ['autorita', 'dataVerbale', 'luogo']),
    },
    {
        id: DOC_IDS.QUIETANZA,
        name: 'Quietanza di Premio',
        description: 'Ricevuta di pagamento del premio assicurativo',
        jsonSchema: objectSchema({
            compagnia: text('Compagnia assicurativa'),
            numeroPolizza: text('Numero polizza'),
            contraente: text('Nome e cognome del contraente'),
            importo: num('Importo pagato in Euro'),
            dataPagamento: date('Data del pagamento'),
            periodoRiferimento: text('Periodo di copertura (es. 01.01.2025 - 01.01.2026)'),
            modalitaPagamento: text('Modalità di pagamento'),
        }, ['compagnia', 'numeroPolizza', 'importo', 'dataPagamento']),
    },
    {
        id: DOC_IDS.DISDETTA,
        name: 'Lettera di Disdetta',
        description: 'Comunicazione di disdetta della polizza assicurativa',
        jsonSchema: objectSchema({
            mittente: text('Nome e cognome / ragione sociale del mittente'),
            codiceFiscaleMittente: codiceFiscale(),
            destinatario: text('Compagnia assicurativa destinataria'),
            numeroPolizza: text('Numero polizza da disdettare'),
            dataEffettoDisdetta: date('Data effetto della disdetta'),
            motivo: text('Motivo della disdetta (se dichiarato)'),
            dataLettera: date('Data della lettera'),
        }, ['mittente', 'numeroPolizza', 'dataEffettoDisdetta']),
    },
    {
        id: DOC_IDS.STATO_FAMIGLIA,
        name: 'Certificato Stato Famiglia',
        description: 'Certificato stato di famiglia — per polizze vita e beneficiari',
        jsonSchema: objectSchema({
            intestatario: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                indirizzo: text('Indirizzo di residenza'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            componenti: arrayOfObjects({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                relazione: text("Relazione con l'intestatario (coniuge, figlio, ecc.)"),
                dataNascita: date('Data di nascita'),
            }, ['nome', 'cognome', 'relazione'], 'Componenti del nucleo familiare'),
            dataRilascio: date('Data di rilascio del certificato'),
            comune: text('Comune che ha rilasciato il certificato'),
        }, ['intestatario', 'componenti']),
    },
    {
        id: DOC_IDS.CERTIFICATO_MORTE,
        name: 'Certificato di Morte',
        description: 'Certificato di morte — per liquidazione polizza vita caso morte',
        jsonSchema: objectSchema({
            defunto: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                dataNascita: date('Data di nascita'),
                luogoNascita: text('Luogo di nascita'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            dataDecesso: date('Data del decesso'),
            luogoDecesso: text('Luogo del decesso'),
            causaDecesso: text('Causa del decesso (se indicata)'),
            comune: text('Comune che ha rilasciato il certificato'),
            dataRilascio: date('Data di rilascio'),
        }, ['defunto', 'dataDecesso', 'luogoDecesso']),
    },
    {
        id: DOC_IDS.SCHEDA_FABBRICATO,
        name: 'Scheda Fabbricato / Immobile',
        description: "Dati dell'immobile assicurato — per polizze casa/incendio",
        jsonSchema: objectSchema({
            proprietario: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            indirizzo: text("Indirizzo completo dell'immobile"),
            comune: text('Comune'), provincia: text('Provincia'),
            tipoImmobile: enumField('Tipo immobile', ['appartamento', 'villa', 'villetta a schiera', 'ufficio', 'negozio', 'capannone', 'altro']),
            superficie: num('Superficie in mq'),
            annoCostruzione: num('Anno di costruzione'),
            valoreRicostruzione: num('Valore di ricostruzione a nuovo in Euro'),
            valoreContenuto: num('Valore del contenuto assicurato in Euro'),
            sistemaAllarme: enumField('Sistema di allarme presente', ['sì', 'no']),
            pianterreno: enumField('Al pianterreno', ['sì', 'no']),
        }, ['proprietario', 'indirizzo', 'tipoImmobile', 'superficie']),
    },
].sort((a, b) => a.name.localeCompare(b.name, 'it'));
