/**
 * US Real Estate — Document Type Definitions
 *
 * Covers the standard US residential real estate transaction workflow:
 * driver's licenses, purchase agreements, deeds, title reports,
 * inspections, appraisals, mortgage and escrow documents.
 *
 * 14 document types for US real estate closings.
 */
import type { DocumentTypeDef } from '../../../types';
import {
    text, num, dateUS, enumField, objectSchema, arrayOfObjects,
    firstName, lastName, ssn, currency, address, parcelNumber,
} from '../../../helpers/us';

// ─── Document IDs ───────────────────────────────────────────────────────────

export const DOC_IDS = {
    DRIVERS_LICENSE: 'doc-drivers-license',
    CONTACT: 'doc-contact',
    PURCHASE_AGREEMENT: 'doc-purchase-agreement',
    DEED: 'doc-deed',
    TITLE_REPORT: 'doc-title-report',
    TITLE_INSURANCE: 'doc-title-insurance',
    CLOSING_DISCLOSURE: 'doc-closing-disclosure',
    INSPECTION_REPORT: 'doc-inspection-report',
    APPRAISAL: 'doc-appraisal',
    MORTGAGE_APPLICATION: 'doc-mortgage-application',
    MORTGAGE_APPROVAL: 'doc-mortgage-approval',
    HOA_DOCS: 'doc-hoa-docs',
    TAX_RECORD: 'doc-tax-record',
    SURVEY: 'doc-survey',
} as const;

// ─── Document Types ─────────────────────────────────────────────────────────

export const documentTypes: DocumentTypeDef[] = [
    {
        id: DOC_IDS.DRIVERS_LICENSE,
        name: "Driver's License / Government ID",
        description: "Government-issued identification: Driver's License, Passport, or State ID",
        isArrayExtraction: true,
        jsonSchema: objectSchema({
            firstName: firstName(), lastName: lastName(),
            middleName: text('Middle name (if present)'),
            dateOfBirth: dateUS('Date of birth'),
            idType: enumField('Type of identification', ["Driver's License", 'Passport', 'State ID']),
            idNumber: text('ID / License number'),
            issueDate: dateUS('Issue date'),
            expirationDate: dateUS('Expiration date'),
            issuingState: text('Issuing state (2-letter abbreviation, e.g. CA, NY, TX)'),
            address: address('Residential address as printed on ID'),
            sex: enumField('Sex', ['M', 'F']),
        }, ['firstName', 'lastName', 'dateOfBirth', 'idType', 'idNumber', 'expirationDate']),
    },
    {
        id: DOC_IDS.CONTACT,
        name: 'Contact Information',
        description: 'Phone, email, and mailing address for a party',
        jsonSchema: objectSchema({
            firstName: firstName(), lastName: lastName(),
            phone: text('Primary phone number'),
            email: { type: 'string', format: 'email', description: 'Email address' },
            mailingAddress: address('Mailing address (if different from residential)'),
            currentAddress: address('Current residential address'),
        }, ['firstName', 'lastName', 'phone', 'email']),
    },
    {
        id: DOC_IDS.PURCHASE_AGREEMENT,
        name: 'Purchase Agreement / Contract',
        description: 'Real estate purchase and sale agreement between buyer and seller',
        jsonSchema: objectSchema({
            seller: objectSchema({
                firstName: firstName(), lastName: lastName(),
                address: address("Seller's address"),
            }, ['firstName', 'lastName']),
            buyer: objectSchema({
                firstName: firstName(), lastName: lastName(),
                address: address("Buyer's address"),
            }, ['firstName', 'lastName']),
            propertyAddress: address('Subject property address'),
            purchasePrice: currency('Purchase price'),
            earnestMoney: currency('Earnest money deposit amount'),
            closingDate: dateUS('Expected closing date'),
            contingencies: text('List of contingencies (inspection, financing, appraisal, etc.)'),
            financingType: enumField('Financing type', ['conventional', 'FHA', 'VA', 'cash', 'other']),
            sellerConcessions: currency('Seller concessions / credits to buyer'),
            personalPropertyIncluded: text('Personal property included (appliances, fixtures, etc.)'),
            closingCostsSplit: text('How closing costs are split between parties'),
            executionDate: dateUS('Date contract was executed / signed'),
        }, ['seller', 'buyer', 'propertyAddress', 'purchasePrice', 'closingDate']),
    },
    {
        id: DOC_IDS.DEED,
        name: 'Deed',
        description: 'Property deed — warranty deed, quitclaim deed, special warranty deed',
        jsonSchema: objectSchema({
            deedType: enumField('Type of deed', ['General Warranty', 'Special Warranty', 'Quitclaim', 'Bargain and Sale', 'Grant Deed']),
            grantor: objectSchema({
                fullName: text('Full legal name of grantor (seller)'),
                address: address("Grantor's address"),
            }, ['fullName']),
            grantee: objectSchema({
                fullName: text('Full legal name of grantee (buyer)'),
                vestingType: text('Vesting / How title is held (e.g. tenants in common, joint tenants)'),
                address: address("Grantee's address"),
            }, ['fullName']),
            legalDescription: text('Full legal description of the property (metes and bounds, lot/block, or plat reference)'),
            propertyAddress: address('Property street address'),
            parcelNumber: parcelNumber(),
            consideration: currency('Consideration / purchase price'),
            recordingDate: dateUS('Date deed was recorded'),
            county: text('County where deed is recorded'),
            bookPage: text('Recording book and page number (e.g. Book 1234, Page 567)'),
        }, ['deedType', 'grantor', 'grantee', 'legalDescription', 'propertyAddress']),
    },
    {
        id: DOC_IDS.TITLE_REPORT,
        name: 'Title Report / Title Search',
        description: 'Preliminary title report or title abstract showing ownership history and encumbrances',
        jsonSchema: objectSchema({
            titleCompany: text('Title company name'),
            effectiveDate: dateUS('Effective date of the title search'),
            currentOwner: text('Current title holder / vested owner'),
            propertyAddress: address('Subject property address'),
            parcelNumber: parcelNumber(),
            legalDescription: text('Legal description of the property'),
            liens: text('Outstanding liens (mortgages, tax liens, judgment liens)'),
            easements: text('Easements and rights of way'),
            encumbrances: text('Other encumbrances or restrictions'),
            taxes: text('Property tax status (current, delinquent, amounts)'),
            exceptions: text('Schedule B exceptions from coverage'),
        }, ['titleCompany', 'currentOwner', 'propertyAddress']),
    },
    {
        id: DOC_IDS.TITLE_INSURANCE,
        name: 'Title Insurance Policy',
        description: "Title insurance commitment or policy (owner's or lender's)",
        jsonSchema: objectSchema({
            insurer: text('Title insurance company'),
            policyNumber: text('Policy or commitment number'),
            policyType: enumField('Policy type', ["owner's", "lender's", 'both']),
            coverageAmount: currency('Coverage amount'),
            premium: currency('Premium amount'),
            insuredParty: text('Name of insured party'),
            effectiveDate: dateUS('Effective date'),
            propertyAddress: address('Insured property address'),
            exceptions: text('Policy exceptions and exclusions'),
        }, ['insurer', 'policyType', 'coverageAmount', 'insuredParty', 'propertyAddress']),
    },
    {
        id: DOC_IDS.CLOSING_DISCLOSURE,
        name: 'Closing Disclosure (CD)',
        description: 'TRID Closing Disclosure — final settlement statement with all costs and credits',
        jsonSchema: objectSchema({
            closingDate: dateUS('Closing date'),
            propertyAddress: address('Property address'),
            seller: objectSchema({
                name: text('Seller full name'), address: address("Seller's address"),
            }, ['name']),
            buyer: objectSchema({
                name: text('Buyer full name'), address: address("Buyer's address"),
            }, ['name']),
            salePrice: currency('Sale price'),
            totalClosingCosts: currency('Total closing costs'),
            buyerClosingCosts: currency("Buyer's total closing costs"),
            sellerClosingCosts: currency("Seller's total closing costs"),
            loanAmount: currency('Loan amount'),
            interestRate: num('Interest rate (%)'),
            monthlyPayment: currency('Monthly principal & interest payment'),
            cashToClose: currency('Cash to close from buyer'),
            sellerProceeds: currency('Net proceeds to seller'),
            prorations: text('Tax and insurance prorations'),
        }, ['closingDate', 'propertyAddress', 'salePrice', 'totalClosingCosts']),
    },
    {
        id: DOC_IDS.INSPECTION_REPORT,
        name: 'Home Inspection Report',
        description: 'Professional home inspection report — structural, mechanical, plumbing, electrical',
        jsonSchema: objectSchema({
            inspector: text('Inspector name and license number'),
            inspectionCompany: text('Inspection company name'),
            inspectionDate: dateUS('Date of inspection'),
            propertyAddress: address('Inspected property address'),
            overallCondition: enumField('Overall condition', ['excellent', 'good', 'fair', 'poor']),
            majorDefects: text('Major defects or safety concerns found'),
            roofCondition: text('Roof condition and estimated remaining life'),
            foundationCondition: text('Foundation / structural condition'),
            plumbing: text('Plumbing system condition'),
            electrical: text('Electrical system condition'),
            hvac: text('HVAC system condition and age'),
            recommendations: text('Recommended repairs or further inspections'),
        }, ['inspector', 'inspectionDate', 'propertyAddress', 'overallCondition']),
    },
    {
        id: DOC_IDS.APPRAISAL,
        name: 'Appraisal Report',
        description: 'Property appraisal — market value determination for lending',
        jsonSchema: objectSchema({
            appraiser: text('Appraiser name and license number'),
            appraisalDate: dateUS('Date of appraisal'),
            propertyAddress: address('Subject property address'),
            appraisedValue: currency('Appraised market value'),
            squareFootage: num('Gross living area (sq ft)'),
            lotSize: text('Lot size (acres or sq ft)'),
            yearBuilt: num('Year built'),
            bedrooms: num('Number of bedrooms'),
            bathrooms: num('Number of bathrooms'),
            condition: enumField('Overall condition', ['C1', 'C2', 'C3', 'C4', 'C5', 'C6']),
            comparables: arrayOfObjects({
                address: address('Comparable property address'),
                salePrice: currency('Sale price'),
                saleDate: dateUS('Sale date'),
                squareFootage: num('Square footage'),
            }, ['address', 'salePrice'], 'Comparable sales used in valuation'),
            approachesUsed: text('Valuation approaches used (Sales Comparison, Cost, Income)'),
        }, ['appraiser', 'appraisalDate', 'propertyAddress', 'appraisedValue']),
    },
    {
        id: DOC_IDS.MORTGAGE_APPLICATION,
        name: 'Mortgage Application (1003)',
        description: 'Uniform Residential Loan Application (URLA / 1003)',
        jsonSchema: objectSchema({
            borrower: objectSchema({
                firstName: firstName(), lastName: lastName(),
                ssn: ssn(), dateOfBirth: dateUS('Date of birth'),
                currentAddress: address('Current address'),
                employer: text('Current employer name'),
                jobTitle: text('Job title / position'),
                yearsEmployed: num('Years at current employer'),
                monthlyIncome: currency('Gross monthly income'),
            }, ['firstName', 'lastName', 'ssn']),
            coBorrower: objectSchema({
                firstName: firstName(), lastName: lastName(),
                ssn: ssn(),
                monthlyIncome: currency('Gross monthly income'),
            }, ['firstName', 'lastName']),
            propertyAddress: address('Subject property address'),
            loanAmount: currency('Requested loan amount'),
            loanType: enumField('Loan type', ['conventional', 'FHA', 'VA', 'USDA']),
            loanPurpose: enumField('Loan purpose', ['purchase', 'refinance', 'construction']),
            loanTerm: num('Loan term (years)'),
            totalAssets: currency('Total assets declared'),
            totalLiabilities: currency('Total liabilities / debts'),
        }, ['borrower', 'propertyAddress', 'loanAmount', 'loanType']),
    },
    {
        id: DOC_IDS.MORTGAGE_APPROVAL,
        name: 'Mortgage Approval / Commitment Letter',
        description: 'Lender commitment or pre-approval letter for mortgage financing',
        jsonSchema: objectSchema({
            lender: text('Lender / bank name'),
            loanOfficer: text('Loan officer name'),
            borrower: text('Borrower full name'),
            approvalDate: dateUS('Date of approval / commitment'),
            approvedAmount: currency('Approved loan amount'),
            interestRate: num('Interest rate (%)'),
            loanType: enumField('Loan type', ['conventional', 'FHA', 'VA', 'USDA', 'jumbo']),
            loanTerm: num('Loan term (years)'),
            conditions: text('Conditions that must be met prior to closing'),
            expirationDate: dateUS('Commitment expiration date'),
            propertyAddress: address('Subject property address'),
        }, ['lender', 'borrower', 'approvedAmount', 'interestRate', 'loanType']),
    },
    {
        id: DOC_IDS.HOA_DOCS,
        name: 'HOA Documents',
        description: 'Homeowners Association documents — CCRs, bylaws, financials, disclosures',
        jsonSchema: objectSchema({
            hoaName: text('HOA / community name'),
            managementCompany: text('Management company name'),
            monthlyDues: currency('Monthly HOA dues'),
            specialAssessments: text('Any pending or recent special assessments'),
            reserves: currency('HOA reserve fund balance'),
            restrictions: text('Key restrictions and covenants'),
            pendingLitigation: text('Any pending litigation or disputes'),
            masterInsurance: text('Master insurance policy coverage'),
        }, ['hoaName', 'monthlyDues']),
    },
    {
        id: DOC_IDS.TAX_RECORD,
        name: 'Property Tax Record',
        description: 'County property tax records — assessed value, tax amounts, payment status',
        jsonSchema: objectSchema({
            parcelNumber: parcelNumber(),
            propertyAddress: address('Property address'),
            owner: text('Property owner name per tax records'),
            assessedValue: currency('Total assessed value'),
            landValue: currency('Assessed land value'),
            improvementValue: currency('Assessed improvement value'),
            annualTax: currency('Annual property tax amount'),
            taxYear: num('Tax year'),
            paymentStatus: enumField('Payment status', ['current', 'delinquent', 'paid in full']),
            exemptions: text('Homestead or other exemptions applied'),
        }, ['parcelNumber', 'propertyAddress', 'assessedValue', 'annualTax']),
    },
    {
        id: DOC_IDS.SURVEY,
        name: 'Property Survey / Plat Map',
        description: 'ALTA/NSPS land survey showing boundaries, improvements, and easements',
        jsonSchema: objectSchema({
            surveyor: text('Surveyor name and license number'),
            surveyDate: dateUS('Date of survey'),
            propertyAddress: address('Property address'),
            parcelNumber: parcelNumber(),
            lotSize: text('Lot size / area (in acres or sq ft)'),
            legalDescription: text('Legal description from survey'),
            boundaryDescription: text('Property boundary details / metes and bounds'),
            improvements: text('Improvements shown (buildings, fences, driveways)'),
            easements: text('Easements identified'),
            encroachments: text('Any encroachments identified'),
            floodZone: text('FEMA flood zone designation (if shown)'),
        }, ['surveyor', 'surveyDate', 'propertyAddress', 'lotSize']),
    },
].sort((a, b) => a.name.localeCompare(b.name, 'en'));
