/**
 * Italy — Shared Field Name Constants
 *
 * Every field name used in entity-type mappings (fieldMappings, matchFields,
 * fieldOrder) should be referenced via this object instead of raw strings.
 * This prevents typos and enables IDE refactoring across all verticals.
 */

export const F = {
    // ── Person / Identity ───────────────────────────────────────────────────
    NOME: 'nome',
    COGNOME: 'cognome',
    CODICE_FISCALE: 'codiceFiscale',
    DATA_NASCITA: 'dataNascita',
    LUOGO_NASCITA: 'luogoNascita',
    INDIRIZZO_RESIDENZA: 'indirizzoDiResidenza',
    STATO_CIVILE: 'statoCivile',
    REGIME_PATRIMONIALE: 'regimePatrimoniale',
    TELEFONO: 'telefono',
    TELEFONO_CELLULARE: 'telefonoCellulare',
    EMAIL: 'email',

    // ── Business ────────────────────────────────────────────────────────────
    PARTITA_IVA: 'partitaIva',
    RAGIONE_SOCIALE: 'ragioneSociale',
    CODICE_ATECO: 'codiceAteco',
    DESCRIZIONE_ATECO: 'descrizioneAteco',
    FORMA_GIURIDICA: 'formaGiuridica',
    CAPITALE_SOCIALE: 'capitaleSociale',
    LEGALE_RAPPRESENTANTE: 'legaleRappresentante',
    SEDE_LEGALE: 'sedeLegale',

    // ── Fiscal / Accounting ─────────────────────────────────────────────────
    ANNO: 'anno',
    REDDITO_COMPLESSIVO: 'redditoComplessivo',
    REDDITO_LORDO: 'redditoLordo',
    IMPOSTA_NETTA: 'impostaNetta',
    FATTURATO: 'fatturato',
    UTILE_ESERCIZIO: 'utileEsercizio',
    REGIME: 'regime',

    // ── Vehicle ─────────────────────────────────────────────────────────────
    TARGA: 'targa',
    TELAIO: 'telaio',
    MARCA: 'marca',
    MODELLO: 'modello',
    ALLESTIMENTO: 'allestimento',
    DATA_IMMATRICOLAZIONE: 'dataImmatricolazione',
    CILINDRATA: 'cilindrata',
    POTENZA_KW: 'potenzaKw',
    ALIMENTAZIONE: 'alimentazione',
    CLASSE_AMBIENTALE: 'classeAmbientale',
    KM: 'km',

    // ── Insurance ───────────────────────────────────────────────────────────
    NUMERO_POLIZZA: 'numeroPolizza',
    COMPAGNIA: 'compagnia',
    RAMO: 'ramo',
    PREMIO_ANNUO: 'premioAnnuo',
    DECORRENZA: 'decorrenza',
    SCADENZA: 'scadenza',
    MASSIMALE: 'massimale',
    GARANZIE: 'garanzie',
    CLASSE_MERITO: 'classeMerito',
    CLASSE_MERITO_PROVENIENZA: 'classeMeritoProvenienza',
    NUMERO_SINISTRO: 'numeroSinistro',
    DATA_SINISTRO: 'dataSinistro',
    LUOGO_SINISTRO: 'luogoSinistro',
    DINAMICA: 'dinamica',
    IMPORTO_RIPARAZIONE: 'importoRiparazione',
    IMPORTO_LIQUIDAZIONE: 'importoLiquidazione',
    COSTO_RIPARAZIONE_EFFETTIVO: 'costoRiparazioneEffettivo',
    DIAGNOSI_LESIONI: 'diagnosiLesioni',
    GIORNI_PROGNOSI: 'giorniPrognosi',
    INVALIDITA_PERMANENTE: 'invaliditaPermanente',
    NUMERO_VERBALE: 'numeroVerbale',
    ULTIMO_PREMIO: 'ultimoPremio',
    ULTIMO_PAGAMENTO: 'ultimoPagamento',

    // ── Real estate / Cadastral ─────────────────────────────────────────────
    FOGLIO: 'foglio',
    PARTICELLA: 'particella',
    SUBALTERNO: 'subalterno',
    SEZIONE: 'sezione',
    COMUNE_CATASTALE: 'comuneCatastale',
    INDIRIZZO: 'indirizzo',
    PIANO: 'piano',
    CATEGORIA: 'categoria',
    CLASSE: 'classe',
    RENDITA: 'rendita',
    CONSISTENZA: 'consistenza',
    SUPERFICIE: 'superficie',
    CLASSE_ENERGETICA: 'classeEnergetica',
    DESTINAZIONE_USO: 'destinazioneUso',
    DESTINAZIONE_URBANISTICA: 'destinazioneUrbanistica',

    // ── Transaction / Financial ─────────────────────────────────────────────
    PREZZO: 'prezzo',
    PREZZO_OFFERTO: 'prezzoOfferto',
    CAPARRA: 'caparra',
    MEDIATORE: 'mediatore',
    PROVVIGIONE: 'provvigione',
    IMPORTO_MUTUO: 'importoMutuo',
    IMPORTO_MUTUO_EROGATO: 'importoMutuoErogato',
    BANCA: 'banca',
    TIPO_TASSO: 'tipoTasso',
    RATA_MENSILE: 'rataMensile',
    TASSO_INTERESSE: 'tassoInteresse',
    IMPORTO_TOTALE: 'importoTotale',
    DATA_STIPULA_PRELIM: 'dataStipulaPrelim',
    MODALITA_PAGAMENTO: 'modalitaPagamento',
    DATA_VENDITA: 'dataVendita',
    VALORE_PERMUTA: 'valorePermuta',
    IMPORTO_FINANZIATO: 'importoFinanziato',
    IMPORTO_RATA: 'importoRata',
    DURATA_RATE_MESI: 'durataRateMesi',
    TAN: 'tan',
    TAEG: 'taeg',
} as const;
