/**
 * Accountant / Tax Firm Italy — Document Type Definitions
 *
 * Covers documents for a commercialista (Italian accountant/tax firm):
 * invoices, tax declarations (730, Redditi PF), F24 payments,
 * CU certifications, payroll, balance sheets, bank statements, ISEE.
 *
 * 14 document types for Italian accounting and tax management.
 */
import type { DocumentTypeDef } from '../../../types';
import {
    text, num, date, enumField, objectSchema, arrayOfObjects,
    nome, cognome, codiceFiscale, partitaIva,
} from '../../../helpers/it';

// ─── Document IDs ───────────────────────────────────────────────────────────

export const DOC_IDS = {
    IDENTITA: 'doc-identita',
    FATTURA: 'doc-fattura',
    RICEVUTA: 'doc-ricevuta',
    CU: 'doc-cu',
    MOD_730: 'doc-730',
    REDDITI_PF: 'doc-redditi-pf',
    F24: 'doc-f24',
    VISURA_CAMERALE: 'doc-visura-camerale',
    BILANCIO: 'doc-bilancio',
    CONTRATTO_LAVORO: 'doc-contratto-lavoro',
    BUSTA_PAGA: 'doc-busta-paga',
    ESTRATTO_CONTO: 'doc-estratto-conto',
    ISEE: 'doc-isee',
    IVA_PERIODICA: 'doc-iva-periodica',
} as const;

// ─── Document Types ─────────────────────────────────────────────────────────

export const documentTypes: DocumentTypeDef[] = [
    {
        id: DOC_IDS.IDENTITA,
        name: "Documento d'Identità",
        description: "Documento di riconoscimento del cliente (CI, Passaporto, Patente)",
        isArrayExtraction: true,
        jsonSchema: objectSchema({
            nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            tipoDocumento: text("Tipo documento: Carta D'Identità, Passaporto, Patente"),
            numeroDocumento: text(''),
            dataEmissione: date('Data di emissione in formato DD.MM.YYYY'),
            dataScadenza: date('Data di scadenza in formato DD.MM.YYYY'),
            rilasciatoDa: text('Autorità che ha rilasciato il documento'),
            luogoNascita: text("Città seguita dalla sigla della provincia tra parentesi tonde — formato: 'NomeCittà (XX)'"),
            dataNascita: date('Data di nascita in formato DD.MM.YYYY'),
            indirizzoDiResidenza: text('Indirizzo completo di residenza'),
        }, ['nome', 'cognome', 'codiceFiscale', 'tipoDocumento', 'numeroDocumento', 'dataEmissione', 'dataScadenza', 'luogoNascita', 'dataNascita']),
    },
    {
        id: DOC_IDS.FATTURA,
        name: 'Fattura',
        description: 'Fattura attiva o passiva — dati emittente, destinatario, imponibile, IVA',
        jsonSchema: objectSchema({
            numero: text('Numero fattura'),
            data: date('Data di emissione fattura'),
            emittente: objectSchema({
                ragioneSociale: text('Ragione sociale o nome dell\'emittente'),
                partitaIva: partitaIva(),
                codiceFiscale: text('Codice fiscale dell\'emittente'),
                indirizzo: text('Indirizzo dell\'emittente'),
            }, ['ragioneSociale', 'partitaIva']),
            destinatario: objectSchema({
                ragioneSociale: text('Ragione sociale o nome del destinatario'),
                partitaIva: partitaIva(),
                codiceFiscale: text('Codice fiscale del destinatario'),
                indirizzo: text('Indirizzo del destinatario'),
            }, ['ragioneSociale']),
            righe: arrayOfObjects({
                descrizione: text('Descrizione del bene/servizio'),
                quantita: num('Quantità'),
                prezzoUnitario: num('Prezzo unitario in Euro'),
                aliquotaIva: num('Aliquota IVA in %'),
                importo: num('Importo totale riga in Euro'),
            }, ['descrizione', 'importo'], 'Righe della fattura'),
            imponibile: num('Totale imponibile in Euro'),
            iva: num('Totale IVA in Euro'),
            totale: num('Totale fattura in Euro'),
            modalitaPagamento: text('Modalità di pagamento'),
            scadenzaPagamento: date('Data scadenza pagamento'),
        }, ['numero', 'data', 'emittente', 'destinatario', 'imponibile', 'totale']),
    },
    {
        id: DOC_IDS.RICEVUTA,
        name: 'Ricevuta / Scontrino',
        description: 'Ricevuta fiscale o scontrino per spese deducibili/detraibili',
        jsonSchema: objectSchema({
            data: date('Data della ricevuta/scontrino'),
            esercente: text('Nome/ragione sociale dell\'esercente'),
            partitaIva: partitaIva(),
            importo: num('Importo totale in Euro'),
            descrizione: text('Descrizione della spesa'),
            tipoPagamento: enumField('Tipo pagamento', ['contanti', 'carta', 'bonifico', 'assegno']),
        }, ['data', 'importo', 'descrizione']),
    },
    {
        id: DOC_IDS.CU,
        name: 'Certificazione Unica (CU)',
        description: 'Certificazione Unica rilasciata dal datore di lavoro / committente',
        jsonSchema: objectSchema({
            anno: num('Anno di riferimento dei redditi'),
            datoreLavoro: objectSchema({
                denominazione: text('Denominazione/ragione sociale del datore'),
                codiceFiscale: text('Codice fiscale del datore'),
                partitaIva: partitaIva(),
            }, ['denominazione', 'codiceFiscale']),
            percipiente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                dataNascita: date('Data di nascita'),
                comuneNascita: text('Comune di nascita'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            redditoLordo: num('Reddito lordo in Euro'),
            ritenuteFiscali: num('Ritenute fiscali operate in Euro'),
            addizionaleRegionale: num('Addizionale regionale in Euro'),
            addizionaleComunale: num('Addizionale comunale in Euro'),
            contributiPrevidenziali: num('Contributi previdenziali trattenuti in Euro'),
            giorniLavorati: num('Numero giorni di lavoro'),
        }, ['anno', 'datoreLavoro', 'percipiente', 'redditoLordo', 'ritenuteFiscali']),
    },
    {
        id: DOC_IDS.MOD_730,
        name: 'Modello 730',
        description: 'Dichiarazione dei redditi semplificata per lavoratori dipendenti e pensionati',
        jsonSchema: objectSchema({
            anno: num('Anno fiscale di riferimento'),
            contribuente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                dataNascita: date('Data di nascita'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            redditoComplessivo: num('Reddito complessivo in Euro'),
            impostaNetta: num('Imposta netta in Euro'),
            detrazioni: num('Totale detrazioni in Euro'),
            risultato: enumField('Risultato della dichiarazione', ['credito', 'debito']),
            importoRimborsoDebito: num('Importo rimborso o debito in Euro'),
            quadriCompilati: text('Elenco dei quadri compilati (es. A, B, C, D, E)'),
            familiari: arrayOfObjects({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                relazione: enumField('Relazione', ['coniuge', 'figlio', 'altro familiare']),
                percentualeCarico: num('Percentuale a carico (es. 100, 50)'),
            }, ['codiceFiscale', 'relazione'], 'Familiari a carico'),
        }, ['anno', 'contribuente', 'redditoComplessivo', 'impostaNetta']),
    },
    {
        id: DOC_IDS.REDDITI_PF,
        name: 'Modello Redditi PF',
        description: 'Dichiarazione dei redditi per persone fisiche con P.IVA o redditi complessi',
        jsonSchema: objectSchema({
            anno: num('Anno fiscale di riferimento'),
            contribuente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                partitaIva: partitaIva(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            regime: enumField('Regime fiscale', ['ordinario', 'forfettario', 'semplificato']),
            redditoComplessivo: num('Reddito complessivo in Euro'),
            impostaNetta: num('Imposta netta in Euro'),
            quadriCompilati: text('Elenco dei quadri compilati'),
            volumeAffari: num('Volume d\'affari in Euro'),
        }, ['anno', 'contribuente', 'redditoComplessivo']),
    },
    {
        id: DOC_IDS.F24,
        name: 'Modello F24',
        description: 'Modello di pagamento unificato per imposte, contributi e premi',
        jsonSchema: objectSchema({
            contribuente: objectSchema({
                codiceFiscale: text('Codice fiscale del contribuente'),
                denominazione: text('Cognome e nome o ragione sociale'),
            }, ['codiceFiscale']),
            dataVersamento: date('Data del versamento'),
            tributi: arrayOfObjects({
                sezione: text('Sezione (Erario, Regioni, IMU, INPS, ecc.)'),
                codiceTributo: text('Codice tributo (es. 4001, 3844, 1040)'),
                rateazione: text('Rateazione/regione/prov./mese rif.'),
                annoRiferimento: text('Anno di riferimento'),
                importoDebito: num('Importo a debito in Euro'),
                importoCredito: num('Importo a credito in Euro'),
            }, ['codiceTributo', 'importoDebito'], 'Elenco tributi/contributi versati'),
            totaleVersato: num('Totale versato in Euro'),
            banca: text('Banca/Posta delegata al pagamento'),
        }, ['contribuente', 'dataVersamento', 'tributi', 'totaleVersato']),
    },
    {
        id: DOC_IDS.VISURA_CAMERALE,
        name: 'Visura Camerale',
        description: 'Visura della Camera di Commercio — dati societari, legale rappresentante, codice ATECO',
        jsonSchema: objectSchema({
            ragioneSociale: text('Ragione sociale / denominazione'),
            partitaIva: partitaIva(),
            codiceFiscale: text('Codice fiscale dell\'impresa'),
            sedeLegale: text('Indirizzo sede legale'),
            legaleRappresentante: text('Nome e cognome del legale rappresentante'),
            cfLegaleRappresentante: codiceFiscale(),
            codiceAteco: text('Codice ATECO principale'),
            descrizioneAteco: text('Descrizione attività ATECO'),
            formaGiuridica: enumField('Forma giuridica', ['SRL', 'SRLS', 'SPA', 'SAS', 'SNC', 'Ditta Individuale', 'Cooperativa']),
            capitaleSociale: num('Capitale sociale in Euro'),
            statoImpresa: enumField('Stato dell\'impresa', ['attiva', 'inattiva', 'cessata', 'in liquidazione']),
            dataIscrizione: date('Data iscrizione alla Camera di Commercio'),
            rea: text('Numero REA'),
        }, ['ragioneSociale', 'partitaIva', 'legaleRappresentante', 'codiceAteco']),
    },
    {
        id: DOC_IDS.BILANCIO,
        name: "Bilancio d'Esercizio",
        description: "Bilancio annuale: stato patrimoniale, conto economico, nota integrativa",
        jsonSchema: objectSchema({
            ragioneSociale: text('Ragione sociale'),
            partitaIva: partitaIva(),
            esercizio: text('Periodo di esercizio (es. 01.01.2025 - 31.12.2025)'),
            anno: num('Anno di competenza'),
            fatturato: num('Ricavi / fatturato in Euro'),
            costiProduzione: num('Costi della produzione in Euro'),
            utileEsercizio: num('Utile (o perdita) d\'esercizio in Euro'),
            totaleAttivo: num('Totale attivo stato patrimoniale in Euro'),
            totalePassivo: num('Totale passivo stato patrimoniale in Euro'),
            patrimonioNetto: num('Patrimonio netto in Euro'),
            risultatoOperativo: num('Risultato operativo (EBIT) in Euro'),
        }, ['ragioneSociale', 'anno', 'fatturato', 'utileEsercizio']),
    },
    {
        id: DOC_IDS.CONTRATTO_LAVORO,
        name: 'Contratto di Lavoro',
        description: 'Contratto di lavoro dipendente — CCNL, livello, RAL',
        jsonSchema: objectSchema({
            datore: objectSchema({
                denominazione: text('Ragione sociale del datore'),
                partitaIva: partitaIva(),
                sedeLegale: text('Sede legale'),
            }, ['denominazione']),
            dipendente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                dataNascita: date('Data di nascita'),
            }, ['nome', 'cognome', 'codiceFiscale']),
            ccnl: text('CCNL applicato (es. Commercio, Metalmeccanico, Studi Professionali)'),
            livello: text('Livello contrattuale (es. 3, 4, Q)'),
            qualifica: text('Qualifica/mansione'),
            tipoContratto: enumField('Tipo contratto', ['indeterminato', 'determinato', 'apprendistato', 'somministrazione', 'collaborazione']),
            dataAssunzione: date('Data di assunzione'),
            dataScadenza: date('Data scadenza (per contratti a termine)'),
            ral: num('Retribuzione Annua Lorda (RAL) in Euro'),
            oreLavoroSettimanali: num('Ore settimanali di lavoro'),
        }, ['datore', 'dipendente', 'ccnl', 'tipoContratto', 'dataAssunzione']),
    },
    {
        id: DOC_IDS.BUSTA_PAGA,
        name: 'Busta Paga / Cedolino',
        description: 'Cedolino paga mensile — lordo, netto, ritenute, contributi',
        jsonSchema: objectSchema({
            datore: text('Denominazione del datore di lavoro'),
            dipendente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            mese: text('Mese di competenza (es. Gennaio 2025)'),
            anno: num('Anno di competenza'),
            retribuzioneLorda: num('Retribuzione lorda del mese in Euro'),
            contributiInps: num('Contributi INPS a carico dipendente in Euro'),
            irpefLorda: num('IRPEF lorda in Euro'),
            detrazioni: num('Detrazioni d\'imposta in Euro'),
            irpefNetta: num('IRPEF netta in Euro'),
            retribuzioneNetta: num('Retribuzione netta (netto in busta) in Euro'),
            tfr: num('Quota TFR maturata nel mese in Euro'),
            oreLavorate: num('Ore lavorate nel mese'),
            oreAssenza: num('Ore di assenza (ferie, malattia, ecc.)'),
        }, ['dipendente', 'mese', 'retribuzioneLorda', 'retribuzioneNetta']),
    },
    {
        id: DOC_IDS.ESTRATTO_CONTO,
        name: 'Estratto Conto Bancario',
        description: 'Estratto conto bancario — saldo, movimenti, periodo',
        jsonSchema: objectSchema({
            banca: text('Nome della banca'),
            iban: text('Codice IBAN'),
            intestatario: text('Intestatario del conto'),
            codiceFiscaleIntestatario: text('Codice fiscale / P.IVA dell\'intestatario'),
            periodo: text('Periodo di riferimento (es. 01.01.2025 - 31.03.2025)'),
            saldoIniziale: num('Saldo iniziale del periodo in Euro'),
            saldoFinale: num('Saldo finale del periodo in Euro'),
            giacenzaMedia: num('Giacenza media nel periodo in Euro'),
            totaleEntrate: num('Totale entrate nel periodo in Euro'),
            totaleUscite: num('Totale uscite nel periodo in Euro'),
        }, ['banca', 'iban', 'intestatario', 'saldoFinale']),
    },
    {
        id: DOC_IDS.ISEE,
        name: 'Attestazione ISEE',
        description: 'Attestazione ISEE — indicatore della situazione economica equivalente',
        jsonSchema: objectSchema({
            anno: num('Anno di riferimento'),
            dichiarante: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            valoreIsee: num('Valore ISEE in Euro'),
            valoreIse: num('Valore ISE in Euro'),
            patrimonioMob: num('Patrimonio mobiliare totale in Euro'),
            patrimonioImm: num('Patrimonio immobiliare totale in Euro'),
            redditoNucleoFamiliare: num('Reddito complessivo del nucleo familiare in Euro'),
            numComponenti: num('Numero componenti nucleo familiare'),
            scalaDiEquivalenza: num('Scala di equivalenza'),
            dataRilascio: date('Data di rilascio attestazione'),
            validita: date('Data di scadenza validità'),
        }, ['anno', 'dichiarante', 'valoreIsee']),
    },
    {
        id: DOC_IDS.IVA_PERIODICA,
        name: 'Liquidazione IVA Periodica',
        description: 'Comunicazione liquidazione periodica IVA — mensile o trimestrale',
        jsonSchema: objectSchema({
            contribuente: objectSchema({
                denominazione: text('Denominazione / ragione sociale'),
                partitaIva: partitaIva(),
                codiceFiscale: text('Codice fiscale'),
            }, ['partitaIva']),
            anno: num('Anno di riferimento'),
            periodo: text('Periodo: mese o trimestre (es. T1, T2, Gennaio, ecc.)'),
            ivaEsigibile: num('IVA a debito (sulle vendite) in Euro'),
            ivaDetratta: num('IVA a credito (sugli acquisti) in Euro'),
            ivaVersata: num('IVA versata nel periodo in Euro'),
            saldo: num('Saldo IVA (debito se positivo, credito se negativo) in Euro'),
            creditoPrecedente: num('Credito periodo precedente in Euro'),
        }, ['contribuente', 'anno', 'periodo', 'ivaEsigibile', 'ivaDetratta', 'saldo']),
    },
].sort((a, b) => a.name.localeCompare(b.name, 'it'));
