/**
 * Car Dealership Italy — Document Type Definitions
 *
 * Covers the standard Italian car dealership document workflow:
 * identity, vehicle registration, certificates, sales contracts, financing.
 *
 * 16 document types for auto sales and ownership transfer.
 */
import type { DocumentTypeDef } from '../../../types';
import {
    text, num, date, enumField, objectSchema, arrayOfObjects,
    nome, cognome, codiceFiscale, statoCivile, targa, telaio,
} from '../../../helpers/it';

// ─── Document IDs ───────────────────────────────────────────────────────────

export const DOC_IDS = {
    IDENTITA: 'doc-identita',
    TESSERA_SANITARIA: 'doc-tessera-sanitaria',
    CONTATTO: 'doc-contatto',
    LIBRETTO: 'doc-libretto-circolazione',
    CDP: 'doc-certificato-proprieta',
    VISURA_PRA: 'doc-visura-pra',
    ATTO_VENDITA: 'doc-atto-vendita',
    BOLLO: 'doc-bollo',
    ASSICURAZIONE: 'doc-assicurazione',
    REVISIONE: 'doc-revisione',
    FINANZIAMENTO: 'doc-finanziamento',
    PERMUTA: 'doc-permuta',
    PROCURA: 'doc-procura',
    VISURA_CAMERALE: 'doc-visura-camerale',
    GARANZIA: 'doc-garanzia',
    SCHEDA_TECNICA: 'doc-scheda-tecnica',
} as const;

// ─── Document Types ─────────────────────────────────────────────────────────

export const documentTypes: DocumentTypeDef[] = [
    {
        id: DOC_IDS.IDENTITA,
        name: "Documento d'Identità",
        description: "Documento di riconoscimento (CI, Passaporto, Patente) per identificazione e Antiriciclaggio",
        isArrayExtraction: true,
        jsonSchema: objectSchema({
            nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            tipoDocumento: text("Tipo documento: Carta D'Identità, Passaporto, Patente"),
            numeroDocumento: text(''),
            dataEmissione: date('Data di emissione in formato DD.MM.YYYY'),
            dataScadenza: date('Data di scadenza in formato DD.MM.YYYY'),
            rilasciatoDa: text('Autorità che ha rilasciato il documento'),
            luogoNascita: text("Città seguita dalla sigla della provincia tra parentesi tonde — formato: 'NomeCittà (XX)'"),
            dataNascita: date('Data di nascita in formato DD.MM.YYYY'),
            indirizzoDiResidenza: text('Indirizzo completo di residenza — formato: Via/Piazza Nome Numero, CAP Città (Provincia)'),
            statoCivile: statoCivile(),
        }, ['nome', 'cognome', 'codiceFiscale', 'tipoDocumento', 'numeroDocumento', 'dataEmissione', 'dataScadenza', 'luogoNascita', 'dataNascita']),
    },
    {
        id: DOC_IDS.TESSERA_SANITARIA,
        name: 'Tessera Sanitaria',
        description: 'Tessera sanitaria / Codice Fiscale — conferma CF e dati anagrafici',
        isArrayExtraction: true,
        jsonSchema: objectSchema({
            nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
            sesso: enumField('Sesso', ['M', 'F']),
            dataNascita: date('Data di nascita'),
            luogoNascita: text('Comune di nascita'),
            dataScadenza: date('Data di scadenza'),
        }, ['nome', 'cognome', 'codiceFiscale', 'sesso', 'dataNascita']),
    },
    {
        id: DOC_IDS.CONTATTO,
        name: 'Documento di Contatto',
        description: 'Recapiti e indirizzi del cliente',
        jsonSchema: objectSchema({
            nome: nome(), cognome: cognome(),
            telefonoCellulare: text('Numero di cellulare principale'),
            telefonoFisso: text('Eventuale numero fisso/ufficio'),
            email: { type: 'string', format: 'email', description: 'Indirizzo email' },
            pec: { type: 'string', format: 'email', description: 'Posta Elettronica Certificata' },
            indirizzoResidenza: text('Via/Piazza e numero civico'),
            cittaResidenza: text('Comune di residenza'),
            cap: text('Codice Avviamento Postale'),
            provincia: text('Sigla Provincia (es. MI, RM)'),
        }, ['nome', 'cognome', 'telefonoCellulare', 'email', 'indirizzoResidenza']),
    },
    {
        id: DOC_IDS.LIBRETTO,
        name: 'Libretto di Circolazione',
        description: 'Carta di circolazione del veicolo con dati tecnici e intestatario',
        jsonSchema: objectSchema({
            targa: targa(), telaio: telaio(),
            marca: text('Marca del veicolo (es. FIAT, BMW, Audi)'),
            modello: text('Modello del veicolo (es. Panda, Serie 3, A4)'),
            allestimento: text('Versione/allestimento se presente'),
            cilindrata: num('Cilindrata in cc'),
            potenzaKw: num('Potenza in kW'),
            alimentazione: enumField('Tipo alimentazione', ['benzina', 'diesel', 'GPL', 'metano', 'ibrido', 'elettrico']),
            dataImmatricolazione: date('Data di prima immatricolazione'),
            massamassimaKg: num('Massa complessiva in kg'),
            posti: num('Numero posti a sedere'),
            intestatario: text('Nome e cognome/ragione sociale intestatario'),
            codiceFiscaleIntestatario: codiceFiscale(),
            classeAmbientale: text('Classe ambientale (es. Euro 6, Euro 5)'),
        }, ['targa', 'telaio', 'marca', 'modello', 'dataImmatricolazione', 'intestatario', 'codiceFiscaleIntestatario']),
    },
    {
        id: DOC_IDS.CDP,
        name: 'Certificato di Proprietà (CDP)',
        description: 'Certificato di proprietà digitale (CDPD) — attesta la titolarità del veicolo al PRA',
        jsonSchema: objectSchema({
            targa: targa(), telaio: telaio(),
            proprietario: text('Nome e cognome / ragione sociale del proprietario'),
            codiceFiscaleProprietario: codiceFiscale(),
            dataAcquisto: date("Data dell'ultima formalità di acquisto"),
            formalita: text('Tipo formalità (es. compravendita, successione, prima iscrizione)'),
            vincoli: text('Eventuali vincoli annotati (fermo amministrativo, ipoteca, leasing)'),
            note: text('Annotazioni aggiuntive'),
        }, ['targa', 'telaio', 'proprietario', 'codiceFiscaleProprietario']),
    },
    {
        id: DOC_IDS.VISURA_PRA,
        name: 'Visura PRA',
        description: 'Visura del Pubblico Registro Automobilistico — gravami, fermi, ipoteche',
        jsonSchema: objectSchema({
            targa: targa(), telaio: telaio(),
            proprietario: text('Proprietario attuale'),
            codiceFiscaleProprietario: codiceFiscale(),
            fermoAmministrativo: enumField('Fermo amministrativo presente', ['sì', 'no']),
            ipoteche: text('Eventuali ipoteche iscritte'),
            gravami: text('Elenco gravami risultanti'),
            dataVisura: date('Data della visura'),
        }, ['targa', 'proprietario', 'fermoAmministrativo']),
    },
    {
        id: DOC_IDS.ATTO_VENDITA,
        name: 'Atto di Vendita / Passaggio di Proprietà',
        description: 'Contratto di compravendita veicolo con dati delle parti e del veicolo',
        jsonSchema: objectSchema({
            venditore: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                indirizzo: text('Indirizzo di residenza del venditore'),
                statoCivile: statoCivile(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            acquirente: objectSchema({
                nome: nome(), cognome: cognome(), codiceFiscale: codiceFiscale(),
                indirizzo: text("Indirizzo di residenza dell'acquirente"),
                statoCivile: statoCivile(),
            }, ['nome', 'cognome', 'codiceFiscale']),
            targa: targa(), telaio: telaio(),
            marca: text('Marca del veicolo'),
            modello: text('Modello del veicolo'),
            prezzo: num('Prezzo di vendita in Euro'),
            dataVendita: date("Data di stipula dell'atto"),
            km: num('Chilometraggio dichiarato al momento della vendita'),
            modalitaPagamento: text('Modalità di pagamento (contanti, bonifico, finanziamento, ecc.)'),
        }, ['venditore', 'acquirente', 'targa', 'prezzo', 'dataVendita']),
    },
    {
        id: DOC_IDS.BOLLO,
        name: 'Attestazione Pagamento Bollo',
        description: 'Ricevuta pagamento tassa automobilistica',
        jsonSchema: objectSchema({
            targa: targa(),
            anno: num('Anno di riferimento del bollo'),
            importo: num('Importo pagato in Euro'),
            dataScadenza: date('Data scadenza del bollo'),
            dataPagamento: date('Data del pagamento'),
        }, ['targa', 'anno', 'importo']),
    },
    {
        id: DOC_IDS.ASSICURAZIONE,
        name: 'Polizza Assicurativa RCA',
        description: 'Certificato di assicurazione obbligatoria RC Auto',
        jsonSchema: objectSchema({
            compagnia: text('Compagnia assicurativa'),
            numeroPolizza: text('Numero polizza'),
            targa: targa(),
            contraente: text('Nome e cognome / ragione sociale del contraente'),
            codiceFiscaleContraente: codiceFiscale(),
            decorrenza: date('Data decorrenza copertura'),
            scadenza: date('Data scadenza copertura'),
            massimale: text('Massimale di copertura'),
            premio: num('Premio annuale in Euro'),
            classeMerito: text('Classe di merito (classe bonus/malus)'),
        }, ['compagnia', 'numeroPolizza', 'targa', 'contraente', 'scadenza']),
    },
    {
        id: DOC_IDS.REVISIONE,
        name: 'Certificato di Revisione',
        description: 'Esito della revisione ministeriale del veicolo',
        jsonSchema: objectSchema({
            targa: targa(),
            dataRevisione: date('Data della revisione'),
            esito: enumField('Esito della revisione', ['REGOLARE', 'RIPETERE', 'SOSPESO']),
            kmRevisione: num('Chilometraggio alla revisione'),
            scadenzaProssimaRevisione: date('Data scadenza prossima revisione'),
            centroRevisione: text('Denominazione del centro revisione'),
        }, ['targa', 'dataRevisione', 'esito']),
    },
    {
        id: DOC_IDS.FINANZIAMENTO,
        name: 'Contratto di Finanziamento',
        description: 'Contratto di finanziamento per acquisto veicolo (prestito, leasing)',
        jsonSchema: objectSchema({
            finanziaria: text('Nome della finanziaria / banca'),
            numeroContratto: text('Numero contratto'),
            importoFinanziato: num('Importo finanziato in Euro'),
            durataRateMesi: num('Durata in mesi'),
            importoRata: num('Importo rata mensile in Euro'),
            tan: num('Tasso Annuo Nominale (TAN) in %'),
            taeg: num('Tasso Annuo Effettivo Globale (TAEG) in %'),
            anticipoVersato: num('Anticipo versato in Euro'),
            maxiRataFinale: num('Eventuale maxi-rata finale / valore futuro garantito in Euro'),
            nomeCliente: text('Nome e cognome del cliente finanziato'),
            codiceFiscaleCliente: codiceFiscale(),
            targa: targa(),
        }, ['finanziaria', 'importoFinanziato', 'durataRateMesi', 'importoRata', 'nomeCliente', 'codiceFiscaleCliente']),
    },
    {
        id: DOC_IDS.PERMUTA,
        name: 'Dichiarazione di Permuta',
        description: 'Dichiarazione relativa al veicolo ritirato in permuta',
        jsonSchema: objectSchema({
            targaRitirato: targa(),
            marcaRitirato: text('Marca del veicolo ritirato'),
            modelloRitirato: text('Modello del veicolo ritirato'),
            kmRitirato: num('Chilometraggio del veicolo ritirato'),
            valorePermuta: num('Valore riconosciuto per la permuta in Euro'),
            proprietarioRitirato: text('Nome e cognome proprietario del veicolo ritirato'),
            codiceFiscaleProprietario: codiceFiscale(),
        }, ['targaRitirato', 'marcaRitirato', 'modelloRitirato', 'valorePermuta', 'proprietarioRitirato']),
    },
    {
        id: DOC_IDS.PROCURA,
        name: 'Procura',
        description: 'Mandato a rappresentare — usata quando il passaggio è fatto per delega',
        jsonSchema: objectSchema({
            nomeMandante: nome(), cognomeMandante: cognome(),
            codiceFiscaleMandante: codiceFiscale(),
            nomeMandatario: nome(), cognomeMandatario: cognome(),
            codiceFiscaleMandatario: codiceFiscale(),
            oggetto: text('Oggetto della procura (es. vendita/acquisto veicolo targa XX000YY)'),
            dataStipula: date('Data della procura'),
        }, ['nomeMandante', 'cognomeMandante', 'codiceFiscaleMandante', 'nomeMandatario', 'cognomeMandatario', 'oggetto']),
    },
    {
        id: DOC_IDS.VISURA_CAMERALE,
        name: 'Visura Camerale',
        description: 'Visura CCIAA — necessaria quando venditore o acquirente è persona giuridica',
        jsonSchema: objectSchema({
            ragioneSociale: text('Ragione sociale / denominazione'),
            partitaIva: text('Partita IVA'),
            codiceFiscale: text("Codice fiscale dell'impresa"),
            sedeLegale: text('Indirizzo sede legale'),
            legaleRappresentante: text('Nome e cognome del legale rappresentante'),
            cfLegaleRappresentante: codiceFiscale(),
            codiceAteco: text('Codice ATECO principale'),
            statoImpresa: enumField("Stato dell'impresa", ['attiva', 'inattiva', 'cessata', 'in liquidazione']),
            dataIscrizione: date('Data iscrizione alla Camera di Commercio'),
            rea: text('Numero REA'),
        }, ['ragioneSociale', 'partitaIva', 'legaleRappresentante']),
    },
    {
        id: DOC_IDS.GARANZIA,
        name: 'Certificato di Garanzia',
        description: 'Garanzia convenzionale o legale sul veicolo (nuovi e usati)',
        jsonSchema: objectSchema({
            tipoGaranzia: enumField('Tipo garanzia', ['legale', 'convenzionale', 'estesa']),
            durataMesi: num('Durata garanzia in mesi'),
            kmLimite: num('Limite chilometrico della garanzia'),
            copertura: text('Descrizione della copertura (motore, cambio, elettronica, ecc.)'),
            esclusioni: text('Eventuali esclusioni dalla garanzia'),
            targa: targa(),
            dataDecorrenza: date('Data decorrenza garanzia'),
        }, ['tipoGaranzia', 'durataMesi', 'targa']),
    },
    {
        id: DOC_IDS.SCHEDA_TECNICA,
        name: 'Scheda Tecnica Veicolo',
        description: 'Scheda tecnica/commerciale del veicolo con optionals e allestimento',
        jsonSchema: objectSchema({
            marca: text('Marca'), modello: text('Modello'),
            allestimento: text('Livello di allestimento (es. Lounge, Sport, Executive)'),
            annoModello: num('Anno modello'),
            coloreEsterno: text('Colore carrozzeria'),
            coloreInterno: text('Colore e materiale interni'),
            optionals: text('Lista optionals inclusi (separati da virgola)'),
            prezzoListino: num('Prezzo di listino in Euro'),
        }, ['marca', 'modello']),
    },
].sort((a, b) => a.name.localeCompare(b.name, 'it'));
